TOP_DIR = ..
ARCH = $(shell uname -m)
ifneq ("$(ARCH)", "ppc64")
ifneq ("$(ARCH)", "ppc64le")
        ifeq ($(BIG),1)
          CROSS_COMPILE ?= powerpc64-linux-gnu-
        else
          CROSS_COMPILE ?= powerpc64le-linux-gnu-
        endif
        endif
        endif

CC = $(CROSS_COMPILE)gcc
LD = $(CROSS_COMPILE)ld
OBJCOPY = $(CROSS_COMPILE)objcopy

CFLAGS = -Os -g -Wall -std=c99 -nostdinc -msoft-float -mno-string -mno-multiple -mno-vsx -mno-altivec -fno-stack-protector -mstrict-align -ffreestanding -fdata-sections -ffunction-sections -I $(TOP_DIR)/include -isystem $(shell $(CC) -print-file-name=include)
ifeq ($(BIG),1)
CFLAGS += -mcpu=power8 -mbig-endian -mabi=elfv2
else
CFLAGS += -mlittle-endian
endif
ASFLAGS = $(CFLAGS)
LDFLAGS = -T powerpc.lds

all: $(TEST).bin

console.o: $(TOP_DIR)/lib/console.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

$(TEST).elf: $(TEST).o head.o console.o
	$(LD) $(LDFLAGS) -o $(TEST).elf $(TEST).o head.o console.o

$(TEST).bin: $(TEST).elf
	$(OBJCOPY) -O binary $(TEST).elf $(TEST).bin

clean:
	@rm -f *.o $(TEST).elf $(TEST).bin $(TEST).hex

QEMU ?= qemu-system-ppc64
ENDIANNESS ?= ,endianness=little

check:
	$(QEMU) -M powernv9$(ENDIANNESS) -bios $(TEST).bin -serial mon:stdio -nographic
check-pseries:
	$(QEMU) -M pseries$(ENDIANNESS) -bios $(TEST).bin -serial mon:stdio -nographic
